CREATE DATABASE IF NOT EXISTS leveret CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE leveret;

CREATE TABLE IF NOT EXISTS User (
    id BIGINT UNSIGNED PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS Tag (
    name VARCHAR(768) PRIMARY KEY NOT NULL,

    owner BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (owner) REFERENCES User(id),

    type ENUM('txt', 'js', 'alias') NOT NULL DEFAULT 'txt',
    body TEXT(32768) NOT NULL
);

CREATE TRIGGER IF NOT EXISTS tag_user_cascade_insert BEFORE INSERT ON Tag FOR EACH ROW
INSERT INTO User(id) VALUES (NEW.owner)
ON DUPLICATE KEY UPDATE id=id;
